from enum import Enum


class UserRole(str, Enum):
    MAIN_LEADER = "MAIN_LEADER"
    WING_LEADER = "WING_LEADER"


class NotificationType(str, Enum):
    BIRTHDAY_TOMORROW = "BIRTHDAY_TOMORROW"
    BIRTHDAY_TODAY = "BIRTHDAY_TODAY"
    NEW_STUDENT = "NEW_STUDENT"
    SYSTEM_NOTIFICATION = "SYSTEM_NOTIFICATION"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    CREATE_STUDENT = "CREATE_STUDENT"
    UPDATE_STUDENT = "UPDATE_STUDENT"
    DELETE_STUDENT = "DELETE_STUDENT"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
    PUSH_SUBSCRIPTION_ADD = "PUSH_SUBSCRIPTION_ADD"
    PUSH_SUBSCRIPTION_REMOVE = "PUSH_SUBSCRIPTION_REMOVE"
